import { GameConfig } from '../types';

export const GAME_CONFIGS: GameConfig[] = [
  {
    id: 'skyjo',
    name: 'Skyjo',
    emoji: '❄️',
    themeColor: '#085041',
    minPlayers: 2,
    maxPlayers: 8,
    scoreDirection: 'low',
    endCondition: 'threshold',
    endValue: 100,
    orderMatters: false,
    inputType: 'simple',
    specialRules: { doubleIfNotMin: true },
  },
  {
    id: 'skullking',
    name: 'Skull King',
    emoji: '☠️',
    themeColor: '#3C3489',
    minPlayers: 2,
    maxPlayers: 8,
    scoreDirection: 'high',
    endCondition: 'fixed',
    endValue: 10,
    orderMatters: true,
    inputType: 'bid',
    specialRules: { bonus14: true, mermaid: true, pirate: true },
  },
  {
    id: 'flip7',
    name: 'Flip 7',
    emoji: '🃏',
    themeColor: '#633806',
    minPlayers: 2,
    maxPlayers: 6,
    scoreDirection: 'high',
    endCondition: 'threshold',
    endValue: 200,
    orderMatters: false,
    inputType: 'bonus',
    specialRules: { multiplierX2: true, plus4: true, plus8: true, plus15: true },
  },
  {
    id: 'uno',
    name: 'UNO',
    emoji: '🎴',
    themeColor: '#8B0000',
    minPlayers: 2,
    maxPlayers: 10,
    scoreDirection: 'high',
    endCondition: 'threshold',
    endValue: 500,
    orderMatters: false,
    inputType: 'simple',
    specialRules: { reversedMode: false },
  },
  {
    id: 'papayoo',
    name: 'Papayoo',
    emoji: '🥝',
    themeColor: '#444444',
    minPlayers: 3,
    maxPlayers: 8,
    scoreDirection: 'low',
    endCondition: 'rounds',
    endValue: null,
    orderMatters: true,
    inputType: 'simple',
    specialRules: { roundTotal: 250 },
  },
  {
    id: 'odin',
    name: 'Odin',
    emoji: '⚡',
    themeColor: '#1A4C8B',
    minPlayers: 2,
    maxPlayers: 6,
    scoreDirection: 'low',
    endCondition: 'threshold',
    endValue: 15,
    orderMatters: false,
    inputType: 'simple',
    specialRules: {},
  },
  {
    id: 'trio',
    name: 'Trio',
    emoji: '3️⃣',
    themeColor: '#8B5E00',
    minPlayers: 3,
    maxPlayers: 6,
    scoreDirection: 'high',
    endCondition: 'threshold',
    endValue: 3,
    orderMatters: false,
    inputType: 'wins',
    specialRules: {},
  },
  {
    id: 'farkle',
    name: 'Farkle',
    emoji: '🎲',
    themeColor: '#8B4513',
    minPlayers: 2,
    maxPlayers: 8,
    scoreDirection: 'high',
    endCondition: 'threshold',
    endValue: 10000,
    orderMatters: false,
    inputType: 'simple',
    specialRules: { allowNegative: false },
  },
  {
    id: 'rummy',
    name: 'Rummy',
    emoji: '🀄',
    themeColor: '#2E4057',
    minPlayers: 2,
    maxPlayers: 4,
    scoreDirection: 'high',
    endCondition: 'rounds',
    endValue: null,
    orderMatters: false,
    inputType: 'simple',
    specialRules: {},
  },
  {
    id: 'yams',
    name: 'Yams',
    emoji: '🎯',
    themeColor: '#4A4E69',
    minPlayers: 2,
    maxPlayers: 10,
    scoreDirection: 'high',
    endCondition: 'fixed',
    endValue: 13,
    orderMatters: false,
    inputType: 'simple',
    specialRules: { allowNegative: false },
  },
  {
    id: 'belote',
    name: 'Belote',
    emoji: '♠️',
    themeColor: '#1B4332',
    minPlayers: 2,
    maxPlayers: 2,
    scoreDirection: 'high',
    endCondition: 'threshold',
    endValue: 1000,
    orderMatters: true,
    inputType: 'simple',
    specialRules: { allowNegative: false, teamGame: true },
  },
  {
    id: 'tarot',
    name: 'Tarot',
    emoji: '🔮',
    themeColor: '#6B2737',
    minPlayers: 3,
    maxPlayers: 5,
    scoreDirection: 'high',
    endCondition: 'rounds',
    endValue: null,
    orderMatters: true,
    inputType: 'simple',
    specialRules: {},
  },
];

export function getGameConfig(id: string): GameConfig | undefined {
  return GAME_CONFIGS.find(g => g.id === id);
}