import { GameConfig } from '../types';

export const GAME_CONFIGS: GameConfig[] = [
  {
    id: 'skyjo',
    name: 'Skyjo',
    minPlayers: 2,
    maxPlayers: 8,
    scoreDirection: 'low',
    endCondition: 'threshold',
    endValue: 100,
    orderMatters: false,
    inputType: 'simple',
    specialRules: { doubleIfNotMin: true },
  },
  {
    id: 'skullking',
    name: 'Skull King',
    minPlayers: 2,
    maxPlayers: 8,
    scoreDirection: 'high',
    endCondition: 'fixed',
    endValue: 10,
    orderMatters: true,
    inputType: 'bid',
    specialRules: { bonus14: true, mermaid: true, pirate: true },
  },
  {
    id: 'flip7',
    name: 'Flip 7',
    minPlayers: 2,
    maxPlayers: 6,
    scoreDirection: 'high',
    endCondition: 'threshold',
    endValue: 200,
    orderMatters: false,
    inputType: 'bonus',
    specialRules: { multiplierX2: true, plus4: true, plus8: true, plus15: true },
  },
  {
    id: 'uno',
    name: 'UNO',
    minPlayers: 2,
    maxPlayers: 10,
    scoreDirection: 'high',
    endCondition: 'threshold',
    endValue: 500,
    orderMatters: false,
    inputType: 'simple',
    specialRules: { reversedMode: false },
  },
  {
    id: 'papayoo',
    name: 'Papayoo',
    minPlayers: 3,
    maxPlayers: 8,
    scoreDirection: 'low',
    endCondition: 'rounds',
    endValue: null,
    orderMatters: true,
    inputType: 'simple',
    specialRules: { roundTotal: 250 },
  },
  {
    id: 'odin',
    name: 'Odin',
    minPlayers: 2,
    maxPlayers: 6,
    scoreDirection: 'low',
    endCondition: 'threshold',
    endValue: 15,
    orderMatters: false,
    inputType: 'simple',
    specialRules: {},
  },
  {
    id: 'trio',
    name: 'Trio',
    minPlayers: 3,
    maxPlayers: 6,
    scoreDirection: 'high',
    endCondition: 'fixed',
    endValue: null,
    orderMatters: false,
    inputType: 'simple',
    specialRules: { winTracker: true },
  },
];

export function getGameConfig(id: string): GameConfig | undefined {
  return GAME_CONFIGS.find(g => g.id === id);
}